#------------------------------------------------------------------------
# Compiled template generated by the Template Toolkit version 2.21
#------------------------------------------------------------------------

Template::Document->new({
    METADATA => {
        'name' => 'html/SqueezeJS/Strings.js',
        'modtime' => '1601604687',
    },
    BLOCK => sub {
        my $context = shift || die "template sub called without context\n";
        my $stash   = $context->stash;
        my $output  = '';
        my $_tt_error;
        
        eval { BLOCK: {
    $output .=  "/* \n * Globally used Logitech Media Server strings.\n * This file should be PROCESSed if SqueezeJS.UI is used.\n */\n";
#line 5 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'POWER', 'jsId' => '' });
    $output .=  "\n";
#line 6 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'PLAY', 'jsId' => '' });
    $output .=  "\n";
#line 7 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'PAUSE', 'jsId' => '' });
    $output .=  "\n";
#line 8 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'NEXT', 'jsId' => '' });
    $output .=  "\n";
#line 9 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'PREVIOUS', 'jsId' => '' });
    $output .=  "\n";
#line 10 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'CONNECTING_FOR', 'jsId' => '' });
    $output .=  "\n\n";
#line 12 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SHUFFLE', 'jsId' => '' });
    $output .=  "\n";
#line 13 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SHUFFLE_OFF', 'jsId' => 'shuffle0' });
    $output .=  "\n";
#line 14 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SHUFFLE_ON_SONGS', 'jsId' => 'shuffle1' });
    $output .=  "	 \n";
#line 15 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SHUFFLE_ON_ALBUMS', 'jsId' => 'shuffle2' });
    $output .=  "\n\n";
#line 17 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'REPEAT', 'jsId' => '' });
    $output .=  "\n";
#line 18 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'REPEAT_OFF', 'jsId' => 'repeat0' });
    $output .=  "\n";
#line 19 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'REPEAT_ONE', 'jsId' => 'repeat1' });
    $output .=  "	 \n";
#line 20 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'REPEAT_ALL', 'jsId' => 'repeat2' });
    $output .=  "\n\n";
#line 22 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'VOLUME', 'jsId' => 'volume' });
    $output .=  "\nSqueezeJS.Strings['volume'] += '";
#line 23 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $stash->get('stringCOLON');
    $output .=  "';\n";
#line 24 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'VOLUME_LOUDER', 'jsId' => 'volumeup' });
    $output .=  "\n";
#line 25 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'VOLUME_SOFTER', 'jsId' => 'volumedown' });
    $output .=  "\n\n";
#line 27 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'BY', 'jsId' => '' });
    $output .=  "\n";
#line 28 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'FROM', 'jsId' => '' });
    $output .=  "\n";
#line 29 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'COLON', 'jsId' => 'colon' });
    $output .=  " 	\n";
#line 30 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'ON', 'jsId' => 'on' });
    $output .=  "\n";
#line 31 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'OFF', 'jsId' => 'off' });
    $output .=  "\n";
#line 32 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'YES', 'jsId' => '' });
    $output .=  "\n";
#line 33 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'NO', 'jsId' => '' });
    $output .=  "\n\n";
#line 35 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'ALBUM', 'jsId' => '' });
    $output .=  "\n";
#line 36 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'ARTIST', 'jsId' => '' });
    $output .=  "\n";
#line 37 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'YEAR', 'jsId' => '' });
    $output .=  "\n\n";
#line 39 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'CLOSE', 'jsId' => '' });
    $output .=  "\n";
#line 40 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'CANCEL', 'jsId' => '' });
    $output .=  "\n";
#line 41 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'CHOOSE_PLAYER', 'jsId' => '' });
    $output .=  "\n";
#line 42 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SYNCHRONIZE', 'jsId' => '' });
    $output .=  "\n";
#line 43 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SETUP_SYNCHRONIZE_DESC', 'jsId' => '' });
    $output .=  "\n";
#line 44 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SETUP_NO_SYNCHRONIZATION', 'jsId' => '' });
    $output .=  "\n";
#line 45 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'NO_PLAYER_FOUND', 'jsId' => 'no_player' });
    $output .=  "\n";
#line 46 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'NO_PLAYER_DETAILS', 'jsId' => '' });
    $output .=  "\n";
#line 47 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SQUEEZENETWORK' });
    $output .=  "\n";
#line 48 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SQUEEZEBOX_SERVER' });
    $output .=  "\n";
#line 49 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SQUEEZEBOX_SERVER_WANT_SWITCH', 'jsId' => 'sc_want_switch' });
    $output .=  "\n";
#line 50 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'BROWSE', 'jsId' => '' });
    $output .=  "\n";
#line 51 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SETUP_SELECT_FOLDER', 'jsId' => 'choose_folder' });
    $output .=  "\n";
#line 52 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    $output .=  $context->process('jsString', { 'id' => 'SETUP_SELECT_FILE', 'jsId' => 'choose_file' });
    $output .=  "\n\nif (Ext.MessageBox) {\n	Ext.MessageBox.buttonText.yes = '";
#line 55 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    
    # FILTER
    $output .=  do {
        my $output = '';
        my $_tt_filter = $context->filter('string')
                  || $context->throw($context->error);
    
    $output .=  'YES';
        
        &$_tt_filter($output);
    };
    
    $output .=  "';\n	Ext.MessageBox.buttonText.no = '";
#line 56 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    
    # FILTER
    $output .=  do {
        my $output = '';
        my $_tt_filter = $context->filter('string')
                  || $context->throw($context->error);
    
    $output .=  'NO';
        
        &$_tt_filter($output);
    };
    
    $output .=  "';\n	Ext.MessageBox.buttonText.cancel = '";
#line 57 "/LMS/logitechmediaserver-8.3.0-1644703639-noCPAN/HTML/EN/html/SqueezeJS/Strings.js"
    
    # FILTER
    $output .=  do {
        my $output = '';
        my $_tt_filter = $context->filter('string')
                  || $context->throw($context->error);
    
    $output .=  'CANCEL';
        
        &$_tt_filter($output);
    };
    
    $output .=  "';\n}";
        } };
        if ($@) {
            $_tt_error = $context->catch($@, \$output);
            die $_tt_error unless $_tt_error->type eq 'return';
        }
    
        return $output;
    },
    DEFBLOCKS => {

    },
});
